import Head from 'next/head'
import Image from 'next/image'
import styles from './index.module.scss'

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { NextPageContext } from 'next'
import { useTranslation } from 'next-i18next'
import SearchForm from '../components/search-form'
export default function Home(props) {
  const { t } = useTranslation('common')
  console.log(props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="hero is-primary is-fullheight">
        <div className="hero-head">
          header
        </div>
        <div className="hero-body">
          <div className="container">
            <h1 className="title is-1 is-uppercase has-text-centered">{t('title')}</h1>
            <SearchForm />
          </div>
        </div>
        <div className="hero-foot">
          footer
        </div>
      </section>
    </>
  )
}

export async function getStaticProps({ locale }: NextPageContext) {
  console.log('locale', locale)
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ['common'])),
    },
  }
}