import Head from 'next/head'
import SearchForm from '../components/search-form/search-form'

import { NextPageContext } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import styles from './index.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <section className={`hero is-primary is-fullheight-with-navbar ${styles.hero}`}>
          <div className="hero-body">
            <div className="container">
              <h1 className="title is-size-2 is-uppercase">Bus tickets to everywhere in Thailand</h1>
              <SearchForm />
            </div>
          </div>
        </section>
        <section className={`hero is-primary is-fullheight-with-navbar`}>
          <div className="hero-body">
            <div className="container">
              <h1 className="title is-size-2 is-uppercase has-text-centered">This website is still under construction</h1>
            </div>
          </div>
        </section>
    </>
  )
}

export async function getStaticProps({ locale }: NextPageContext) {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'en', ['common'])),
    },
  }
}