import { GetServerSidePropsResult, NextPageContext } from "next"
import Head from "next/head"
import { Trip } from '../types'
import SearchResults from "../components/search-results"
import { searchTrips } from "./api/search"
import { useRouter } from "next/router"
import SearchFormOneLine from "../components/search-form/search-form-one-line"

interface TripPageProps {
  trips: Trip[]
}

const TripPage = ({ trips }: TripPageProps): JSX.Element => {
  const { query } = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="has-background-primary is-full-height">
        <SearchFormOneLine />
        <div className="container p-4">
          <h2 className="is-size-2 has-text-white">Your trips from <b>{query.departure}</b> to <b>{query.destination}</b></h2>
          <SearchResults trips={trips} />
        </div>
      </div>
    </>
  )
}

export default TripPage

export const getServerSideProps = async (context: NextPageContext): Promise<GetServerSidePropsResult<TripPageProps>> => {
  const { departure, destination, departureDate } = context.query
  if (departure && destination && departureDate) {
    const trips = JSON.parse(JSON.stringify((await searchTrips(departure.toString(), destination.toString(), departureDate.toString())))) as Trip[]
    return {
      props: {
        trips
      }
    }     
  }
  return {
    notFound: true
  }

}